import { mkdir,readFile,writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import type { NaturalLanguageBriefInput } from "../src/brief-normalizer.js";
import { assertLosslessSiteGraphRoundTrip,siteGraphFingerprint } from "../src/page-graph-roundtrip.js";
import { compileProductionSite } from "../src/production-site-compiler.js";

const inputs=JSON.parse(await readFile(resolve("fixtures/v2/quality-site-benchmarks.json"),"utf8")) as NaturalLanguageBriefInput[];const outputDirectory=resolve("artifacts/v2/page-graph-roundtrip");await mkdir(outputDirectory,{recursive:true});const rows=[];
for(const input of inputs){const compilation=compileProductionSite(input);const fingerprint=siteGraphFingerprint(compilation.siteGraph);const roundTrip=assertLosslessSiteGraphRoundTrip(compilation.siteGraph);await writeFile(resolve(outputDirectory,`${compilation.siteGraph.project}.puck.json`),`${JSON.stringify(compilation.puckSiteGraph,null,2)}\n`,`utf8`);await writeFile(resolve(outputDirectory,`${compilation.siteGraph.project}.payload.json`),`${JSON.stringify(compilation.payloadSiteGraph,null,2)}\n`,`utf8`);rows.push({project:compilation.siteGraph.project,routes:compilation.siteGraph.routes.map((entry)=>entry.route),source:compilation.siteGraph.source,readiness:compilation.siteGraph.readiness,fingerprint,puckFingerprint:roundTrip.puck,payloadFingerprint:roundTrip.payload});}
const uniqueFingerprints=new Set(rows.map((row)=>row.fingerprint)).size;const overall=rows.length===6&&uniqueFingerprints===6&&rows.every((row)=>row.readiness==="READY"&&row.routes.length>=2&&row.source.mode==="PRODUCTION"&&row.fingerprint===row.puckFingerprint&&row.fingerprint===row.payloadFingerprint)?"PASS":"FAIL";const receipt={schema:"website-design-compiler/site-graph-roundtrip-receipt/v2",overall,siteCount:rows.length,routeCount:rows.reduce((sum,row)=>sum+row.routes.length,0),uniqueFingerprints,rows};await writeFile(resolve(outputDirectory,"receipt.json"),`${JSON.stringify(receipt,null,2)}\n`,`utf8`);console.log(JSON.stringify({overall,siteCount:rows.length,routeCount:receipt.routeCount,uniqueFingerprints}));if(overall!=="PASS")process.exitCode=1;
