import { execFileSync } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { arch, platform, release } from "node:os";
import { join } from "node:path";
import { RELEASE_CHILD_SPECS, readBoundReleaseEvidence, type ReleaseChildName, type ReleaseEvidenceFileBinding } from "../src/release-evidence.js";
import { evaluateReleaseGate } from "../src/release-gate.js";
import { CAPABILITY_RECEIPT_SCHEMAS } from "../src/release-policy-v2.js";
const root=process.cwd();
async function readJson<T>(path:string):Promise<T|null>{try{return JSON.parse(await readFile(path,"utf8")) as T;}catch{return null;}}
function commandVersion(command:string,args:string[]):string{try{return execFileSync(command,args,{cwd:root,encoding:"utf8"}).trim();}catch{return "NOT_EXERCISED";}}
function changedFiles():string[]{try{return execFileSync("git",["diff-tree","--no-commit-id","--name-only","-r",process.env.GITHUB_SHA??"HEAD"],{cwd:root,encoding:"utf8"}).split("\n").map(v=>v.trim()).filter(Boolean).sort();}catch{return [];}}
const expectedGit={sha:process.env.GITHUB_SHA??"",ref:process.env.GITHUB_REF??""};
const evidenceBindings=Object.fromEntries(await Promise.all((Object.entries(RELEASE_CHILD_SPECS) as Array<[ReleaseChildName,(typeof RELEASE_CHILD_SPECS)[ReleaseChildName]]>).map(async([key,spec])=>[key,await readBoundReleaseEvidence(root,spec.path,spec.schema,expectedGit)]))) as Record<ReleaseChildName,ReleaseEvidenceFileBinding>;
const sharedBinding=await readJson<{sourceRepository?:string;sourceIdentity?:string;consumerIdentity?:string;resolutions?:Array<{name?:string;state?:string;identity?:string}>}>(join(root,RELEASE_CHILD_SPECS.shared.path));
const evaluation=evaluateReleaseGate({runtime:evidenceBindings.runtime.state,browser:evidenceBindings.browser.state,accessibilityPerformance:evidenceBindings.quality.state,storybook:evidenceBindings.storybook.state,sharedBindings:evidenceBindings.shared.state,arena:evidenceBindings.arena.state,showcase:evidenceBindings.showcase.state,externalSkills:evidenceBindings.external.state,mediaGenerator:evidenceBindings.media.state,authoringStudio:evidenceBindings.authoring.state,payloadCms:evidenceBindings.cms.state,repositoryRights:evidenceBindings.rights.state});
const optionalEvidence={liveReference:await readBoundReleaseEvidence(root,"artifacts/live-reference/live-reference-receipt.json",CAPABILITY_RECEIPT_SCHEMAS.liveReference,expectedGit),webgpu:await readBoundReleaseEvidence(root,"artifacts/graphics-3d/webgpu-receipt.json",CAPABILITY_RECEIPT_SCHEMAS.webgpu,expectedGit),productionProvider:await readBoundReleaseEvidence(root,"artifacts/media-generator/production-provider-status.json",CAPABILITY_RECEIPT_SCHEMAS.productionProvider,expectedGit)};
const unresolvedRisks=[{id:"reference-live-remote-capture",state:optionalEvidence.liveReference.state,reason:"live third-party URL availability remains opt-in; deterministic SSRF-safe adapter tests are separate from external-site uptime"},{id:"webgpu-tsl",state:optionalEvidence.webgpu.state,reason:"WebGPU/TSL remains an optional capability and requires an exact runtime receipt"},{id:"production-generative-model-rights",state:optionalEvidence.productionProvider.state,reason:"only the deterministic internal mock model is admitted; real image/video/3D model weights and output terms remain review-required until exact rights evidence passes license-provenance"}].filter(r=>r.state!=="PASS");
const commands=["pnpm install --no-frozen-lockfile","pnpm typecheck","pnpm build","pnpm test","pnpm provenance:fixture","pnpm rights:clearance","pnpm compile:fixture","pnpm showcase:compile","pnpm showcase:compiler-receipt","pnpm external-skills:receipt","pnpm media:fixture","pnpm authoring:receipt","pnpm cms:fixture","pnpm ui:typecheck","pnpm ui:build","pnpm browser:typecheck","pnpm storybook:typecheck","pnpm arena:typecheck","pnpm exec playwright install --with-deps chromium","pnpm reference:media-fixture","pnpm reference:browser-fixture","pnpm verify:bindings fixtures/bindings/registry-projection.json skills artifacts/runtime/shared-binding-receipt.json","pnpm storybook:build","pnpm storybook:qa","pnpm storybook:receipt","pnpm browser:qa","pnpm browser:receipt","pnpm quality:receipt","pnpm arena:smoke","pnpm release:receipt"];
const receipt={schema:"website-design-compiler/release-gate-receipt/v2",overall:evaluation.overall,git:{sha:process.env.GITHUB_SHA??"UNBOUND",ref:process.env.GITHUB_REF??"UNBOUND",event:process.env.GITHUB_EVENT_NAME??"UNBOUND",changedFiles:changedFiles()},workflow:{name:process.env.GITHUB_WORKFLOW??"UNBOUND",runId:process.env.GITHUB_RUN_ID??"UNBOUND",runAttempt:process.env.GITHUB_RUN_ATTEMPT??"UNBOUND",job:process.env.GITHUB_JOB??"UNBOUND",commands},environment:{node:process.version,pnpm:commandVersion("pnpm",["--version"]),playwright:commandVersion("pnpm",["exec","playwright","--version"]),platform:platform(),osRelease:release(),arch:arch(),runnerOs:process.env.RUNNER_OS??"UNBOUND",runnerArch:process.env.RUNNER_ARCH??"UNBOUND",imageOs:process.env.ImageOS??"UNBOUND",imageVersion:process.env.ImageVersion??"UNBOUND"},bindings:sharedBinding?{sourceRepository:sharedBinding.sourceRepository??"ABSENT",sourceIdentity:sharedBinding.sourceIdentity??"ABSENT",consumerIdentity:sharedBinding.consumerIdentity??"ABSENT",resolutions:sharedBinding.resolutions??[]}:"ABSENT",gates:evaluation.gates,evidence:Object.fromEntries(Object.values(RELEASE_CHILD_SPECS).map((spec)=>[spec.gate,spec.path])),evidenceBindings,optionalEvidence,unresolvedRisks};
const outputDirectory=join(root,"artifacts/release");await mkdir(outputDirectory,{recursive:true});const outputPath=join(outputDirectory,"release-gate-receipt.json");await writeFile(outputPath,`${JSON.stringify(receipt,null,2)}\n`,"utf8");console.log(JSON.stringify({receiptPath:outputPath,overall:receipt.overall,gates:receipt.gates,unresolvedRiskCount:unresolvedRisks.length}));if(receipt.overall!=="PASS")process.exitCode=1;
