import { execFileSync } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { arch, platform, release } from "node:os";
import { join } from "node:path";
import { evaluateReleaseGate, type ReleaseInputState } from "../src/release-gate.js";
const root=process.cwd();
async function readOverall(path:string):Promise<ReleaseInputState>{try{const value=JSON.parse(await readFile(path,"utf8")) as {overall?:unknown};const state=value.overall;if(state==="PASS"||state==="FAIL"||state==="NOT_IMPLEMENTED"||state==="NOT_EXERCISED"||state==="ABSENT"||state==="SKIPPED_BY_POLICY")return state;return "FAIL";}catch{return "ABSENT";}}
async function readJson<T>(path:string):Promise<T|null>{try{return JSON.parse(await readFile(path,"utf8")) as T;}catch{return null;}}
function commandVersion(command:string,args:string[]):string{try{return execFileSync(command,args,{cwd:root,encoding:"utf8"}).trim();}catch{return "NOT_EXERCISED";}}
function changedFiles():string[]{try{return execFileSync("git",["diff-tree","--no-commit-id","--name-only","-r",process.env.GITHUB_SHA??"HEAD"],{cwd:root,encoding:"utf8"}).split("\n").map(v=>v.trim()).filter(Boolean).sort();}catch{return [];}}
const paths={runtime:join(root,"artifacts/runtime/minimal/runtime-receipt.json"),browser:join(root,"artifacts/browser-qa/browser-qa.json"),quality:join(root,"artifacts/accessibility-performance/accessibility-performance.json"),storybook:join(root,"artifacts/storybook/storybook-workshop.json"),shared:join(root,"artifacts/runtime/shared-binding-receipt.json"),arena:join(root,"artifacts/arena/arena-score.json"),showcase:join(root,"artifacts/showcase/showcase-compiler-receipt.json"),external:join(root,"artifacts/external-skills/registry-receipt.json"),media:join(root,"artifacts/media-generator/media-generation-receipt.json"),authoring:join(root,"artifacts/authoring/authoring-receipt.json"),cms:join(root,"artifacts/cms/payload-cms-receipt.json"),rights:join(root,"artifacts/rights-clearance/clearance-receipt.json")};
const sharedBinding=await readJson<{sourceRepository?:string;sourceIdentity?:string;consumerIdentity?:string;resolutions?:Array<{name?:string;state?:string;identity?:string}>}>(paths.shared);
const project=await readJson<{referenceIntelligence?:Record<string,unknown>;graphics3d?:Record<string,unknown>}>(join(root,"project.json"));
const evaluation=evaluateReleaseGate({runtime:await readOverall(paths.runtime),browser:await readOverall(paths.browser),accessibilityPerformance:await readOverall(paths.quality),storybook:await readOverall(paths.storybook),sharedBindings:await readOverall(paths.shared),arena:await readOverall(paths.arena),showcase:await readOverall(paths.showcase),externalSkills:await readOverall(paths.external),mediaGenerator:await readOverall(paths.media),authoringStudio:await readOverall(paths.authoring),payloadCms:await readOverall(paths.cms),repositoryRights:await readOverall(paths.rights)});
const unresolvedRisks=[{id:"reference-live-remote-capture",state:project?.referenceIntelligence?.liveThirdPartyRemoteCapture??"NOT_EXERCISED",reason:"live third-party URL availability remains opt-in; deterministic SSRF-safe adapter tests are separate from external-site uptime"},{id:"webgpu-tsl",state:project?.graphics3d?.webgpuTsl??"ABSENT",reason:"WebGPU/TSL remains an optional unexercised graphics path"},{id:"production-generative-model-rights",state:"NOT_EXERCISED",reason:"only the deterministic internal mock model is admitted; real image/video/3D model weights and output terms remain review-required until exact rights evidence passes license-provenance"}].filter(r=>r.state!=="PASS");
const commands=["pnpm install --no-frozen-lockfile","pnpm typecheck","pnpm build","pnpm test","pnpm provenance:fixture","pnpm rights:clearance","pnpm compile:fixture","pnpm showcase:compile","pnpm showcase:compiler-receipt","pnpm external-skills:receipt","pnpm media:fixture","pnpm authoring:receipt","pnpm cms:fixture","pnpm ui:typecheck","pnpm ui:build","pnpm browser:typecheck","pnpm storybook:typecheck","pnpm arena:typecheck","pnpm exec playwright install --with-deps chromium","pnpm reference:media-fixture","pnpm reference:browser-fixture","pnpm verify:bindings fixtures/bindings/registry-projection.json skills artifacts/runtime/shared-binding-receipt.json","pnpm storybook:build","pnpm storybook:qa","pnpm storybook:receipt","pnpm browser:qa","pnpm browser:receipt","pnpm quality:receipt","pnpm arena:smoke","pnpm release:receipt"];
const receipt={schema:"website-design-compiler/release-gate-receipt/v2",overall:evaluation.overall,git:{sha:process.env.GITHUB_SHA??"UNBOUND",ref:process.env.GITHUB_REF??"UNBOUND",event:process.env.GITHUB_EVENT_NAME??"UNBOUND",changedFiles:changedFiles()},workflow:{name:process.env.GITHUB_WORKFLOW??"UNBOUND",runId:process.env.GITHUB_RUN_ID??"UNBOUND",runAttempt:process.env.GITHUB_RUN_ATTEMPT??"UNBOUND",job:process.env.GITHUB_JOB??"UNBOUND",commands},environment:{node:process.version,pnpm:commandVersion("pnpm",["--version"]),playwright:commandVersion("pnpm",["exec","playwright","--version"]),platform:platform(),osRelease:release(),arch:arch(),runnerOs:process.env.RUNNER_OS??"UNBOUND",runnerArch:process.env.RUNNER_ARCH??"UNBOUND",imageOs:process.env.ImageOS??"UNBOUND",imageVersion:process.env.ImageVersion??"UNBOUND"},bindings:sharedBinding?{sourceRepository:sharedBinding.sourceRepository??"ABSENT",sourceIdentity:sharedBinding.sourceIdentity??"ABSENT",consumerIdentity:sharedBinding.consumerIdentity??"ABSENT",resolutions:sharedBinding.resolutions??[]}:"ABSENT",gates:evaluation.gates,evidence:{runtime:paths.runtime,browser:paths.browser,accessibilityPerformance:paths.quality,storybook:paths.storybook,sharedBindings:paths.shared,arena:paths.arena,showcase:paths.showcase,externalSkills:paths.external,mediaGenerator:paths.media,authoringStudio:paths.authoring,payloadCms:paths.cms,repositoryRights:paths.rights},unresolvedRisks};
const outputDirectory=join(root,"artifacts/release");await mkdir(outputDirectory,{recursive:true});const outputPath=join(outputDirectory,"release-gate-receipt.json");await writeFile(outputPath,`${JSON.stringify(receipt,null,2)}\n`,"utf8");console.log(JSON.stringify({receiptPath:outputPath,overall:receipt.overall,gates:receipt.gates,unresolvedRiskCount:unresolvedRisks.length}));if(receipt.overall!=="PASS")process.exitCode=1;
