export const SECTION_KINDS = ["navigation","hero","feature-grid","bento-grid","proof-cloud","metrics","testimonial","comparison","pricing","faq","cta","footer","editorial-prose","editorial-media","product-showcase","media-stage","graphics-2d-stage","graphics-3d-stage"] as const;
export type SectionKind = (typeof SECTION_KINDS)[number];
export type SectionFieldType = "text"|"rich-text"|"link"|"items"|"media"|"number";
export interface SectionFieldContract { type: SectionFieldType; required: boolean; provenanceRequired: boolean; maxLength?: number; }
export interface GovernedSectionContract { kind: SectionKind; variants: readonly string[]; fields: Readonly<Record<string,SectionFieldContract>>; rawMarkupAllowed:false; tokenOwnership:"semantic-design-tokens/v2"; claimPolicy:"CLAIM_SAFE"|"EVIDENCE_REQUIRED"; }
const text=(required:boolean,maxLength:number,provenanceRequired=true):SectionFieldContract=>({type:"text",required,provenanceRequired,maxLength});
const items=(required:boolean,provenanceRequired=true):SectionFieldContract=>({type:"items",required,provenanceRequired});
const media=(required=false):SectionFieldContract=>({type:"media",required,provenanceRequired:true});
export const SECTION_CONTRACTS:Readonly<Record<SectionKind,GovernedSectionContract>>={
 navigation:{kind:"navigation",variants:["minimal","product"],fields:{brand:text(true,48),links:items(true),action:{type:"link",required:false,provenanceRequired:true}},rawMarkupAllowed:false,tokenOwnership:"semantic-design-tokens/v2",claimPolicy:"CLAIM_SAFE"},
 hero:{kind:"hero",variants:["text-first","split-media","interactive"],fields:{eyebrow:text(false,48),headline:text(true,96),body:text(true,220),primaryAction:{type:"link",required:true,provenanceRequired:true},secondaryAction:{type:"link",required:false,provenanceRequired:true},media:media(false)},rawMarkupAllowed:false,tokenOwnership:"semantic-design-tokens/v2",claimPolicy:"CLAIM_SAFE"},
 "feature-grid":{kind:"feature-grid",variants:["cards","rows","icon-grid"],fields:{heading:text(true,72),items:items(true)},rawMarkupAllowed:false,tokenOwnership:"semantic-design-tokens/v2",claimPolicy:"CLAIM_SAFE"},
 "bento-grid":{kind:"bento-grid",variants:["balanced","asymmetric"],fields:{heading:text(false,72),items:items(true)},rawMarkupAllowed:false,tokenOwnership:"semantic-design-tokens/v2",claimPolicy:"CLAIM_SAFE"},
 "proof-cloud":{kind:"proof-cloud",variants:["logos","citations"],fields:{heading:text(false,64),items:items(true,true)},rawMarkupAllowed:false,tokenOwnership:"semantic-design-tokens/v2",claimPolicy:"EVIDENCE_REQUIRED"},
 metrics:{kind:"metrics",variants:["inline","grid"],fields:{heading:text(false,64),items:items(true,true)},rawMarkupAllowed:false,tokenOwnership:"semantic-design-tokens/v2",claimPolicy:"EVIDENCE_REQUIRED"},
 testimonial:{kind:"testimonial",variants:["quote","carousel-shell"],fields:{quote:text(true,320,true),attribution:text(true,96,true)},rawMarkupAllowed:false,tokenOwnership:"semantic-design-tokens/v2",claimPolicy:"EVIDENCE_REQUIRED"},
 comparison:{kind:"comparison",variants:["table","matrix"],fields:{heading:text(true,72),items:items(true,true)},rawMarkupAllowed:false,tokenOwnership:"semantic-design-tokens/v2",claimPolicy:"EVIDENCE_REQUIRED"},
 pricing:{kind:"pricing",variants:["tiers","single-offer"],fields:{heading:text(true,72),items:items(true,true)},rawMarkupAllowed:false,tokenOwnership:"semantic-design-tokens/v2",claimPolicy:"EVIDENCE_REQUIRED"},
 faq:{kind:"faq",variants:["accordion","list"],fields:{heading:text(true,72),items:items(true)},rawMarkupAllowed:false,tokenOwnership:"semantic-design-tokens/v2",claimPolicy:"CLAIM_SAFE"},
 cta:{kind:"cta",variants:["band","split"],fields:{headline:text(true,80),body:text(false,180),action:{type:"link",required:true,provenanceRequired:true}},rawMarkupAllowed:false,tokenOwnership:"semantic-design-tokens/v2",claimPolicy:"CLAIM_SAFE"},
 footer:{kind:"footer",variants:["compact","multi-column"],fields:{brand:text(true,48),links:items(true),legal:text(false,160)},rawMarkupAllowed:false,tokenOwnership:"semantic-design-tokens/v2",claimPolicy:"CLAIM_SAFE"},
 "editorial-prose":{kind:"editorial-prose",variants:["article","longform"],fields:{heading:text(false,96),body:{type:"rich-text",required:true,provenanceRequired:true}},rawMarkupAllowed:false,tokenOwnership:"semantic-design-tokens/v2",claimPolicy:"CLAIM_SAFE"},
 "editorial-media":{kind:"editorial-media",variants:["figure","gallery"],fields:{media:media(true),caption:text(false,180)},rawMarkupAllowed:false,tokenOwnership:"semantic-design-tokens/v2",claimPolicy:"CLAIM_SAFE"},
 "product-showcase":{kind:"product-showcase",variants:["split","stage"],fields:{heading:text(true,72),body:text(false,180),media:media(true)},rawMarkupAllowed:false,tokenOwnership:"semantic-design-tokens/v2",claimPolicy:"CLAIM_SAFE"},
 "media-stage":{kind:"media-stage",variants:["image","video"],fields:{media:media(true),description:text(false,180)},rawMarkupAllowed:false,tokenOwnership:"semantic-design-tokens/v2",claimPolicy:"CLAIM_SAFE"},
 "graphics-2d-stage":{kind:"graphics-2d-stage",variants:["ambient","interactive"],fields:{description:text(true,180)},rawMarkupAllowed:false,tokenOwnership:"semantic-design-tokens/v2",claimPolicy:"CLAIM_SAFE"},
 "graphics-3d-stage":{kind:"graphics-3d-stage",variants:["product","spatial"],fields:{description:text(true,180)},rawMarkupAllowed:false,tokenOwnership:"semantic-design-tokens/v2",claimPolicy:"CLAIM_SAFE"}
};
export interface SectionInstance { id:string; kind:SectionKind; variant:string; props:Record<string,unknown>; provenance:Record<string,string>; tokenRef:"semantic-design-tokens/v2"; }
export function validateSectionInstance(instance:SectionInstance):string[]{ const c=SECTION_CONTRACTS[instance.kind]; const e:string[]=[]; if(!c)return[`unknown section kind: ${instance.kind}`]; if(!c.variants.includes(instance.variant))e.push(`unsupported variant ${instance.variant} for ${instance.kind}`); for(const k of Object.keys(instance.props)) if(!(k in c.fields))e.push(`unknown prop ${k} for ${instance.kind}`); for(const [f,r] of Object.entries(c.fields)){const v=instance.props[f]; if(r.required&&(v===undefined||v===null||v===""))e.push(`missing required field ${f}`); if(typeof v==="string"&&r.maxLength!==undefined&&v.length>r.maxLength)e.push(`field ${f} exceeds max length ${r.maxLength}`); if(v!==undefined&&r.provenanceRequired&&!instance.provenance[f])e.push(`missing provenance for ${f}`);} if(instance.props.html!==undefined||instance.props.css!==undefined)e.push("raw markup/style escape hatch forbidden"); return e; }
export function sectionRegistryProjection(){return SECTION_KINDS.map(kind=>({kind,variants:[...SECTION_CONTRACTS[kind].variants],fieldNames:Object.keys(SECTION_CONTRACTS[kind].fields).sort(),claimPolicy:SECTION_CONTRACTS[kind].claimPolicy,rawMarkupAllowed:false,tokenOwnership:"semantic-design-tokens/v2"}));}
